version: '3.3'

services:
  koel:
    container_name: koel
    image: phanan/koel
    depends_on:
      - koeldb
    restart: always
    networks:
      - koelnet
    ports:
      - '8080:80'
    environment:
      - DB_CONNECTION=pgsql
      # - DB_CONNECTION=mysql
      - DB_HOST=koeldb
      - DB_USERNAME=koel
      - DB_PASSWORD=koelpassword
      - DB_DATABASE=koel
    volumes:
      - ./music:/music
      - ./.env:/var/www/html/.env
      - ./covers:/var/www/html/public/img/covers
      - ./search_indexes:/var/www/html/storage/search-indexes

  koeldb:
    container_name: koeldb
    image: postgres:13
    # image: mysql/mysql-server:8.0
    restart: always
    networks:
      - koelnet
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    #  - db:/var/lib/mysql
    environment:
      - POSTGRES_DB=koel
      - POSTGRES_USER=koel
      - POSTGRES_PASSWORD=koelpassword
    #  - MYSQL_ROOT_PASSWORD=rootpassword
    #  - MYSQL_DATABASE=koel
    #  - MYSQL_USER=koel
    #  - MYSQL_PASSWORD=koelpassword
volumes:
  db:
    driver: local
networks:
  koelnet:
    external: true
